### ISSUE TITLE
Feedback-formen fungerer ikke

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#129]
**[Original report](https://bitbucket.org/webkom/deprecated-nablaweb/issue/129) by Andreas Røssland (Bitbucket: [557058:06d22f7f-1c1a-4687-a750-e16dfe1eae15](https://bitbucket.org/557058:06d22f7f-1c1a-4687-a750-e16dfe1eae15), GitHub: [roessland](https://github.com/roessland)).**

----------------------------------------

```
TypeError at /feedback/
argument of type 'NoneType' is not iterable
```

Alternativ: 

1. Fikse
2. Bytte ut med webkom-epost
3. Bytte ut med Google Docs

**Comment by ggjersund** [comment]
@kaprests Hva er status på feedback formen? Kan vi lukke denne bug issuen?

**Comment by ggjersund** [comment]
Fikset :)
