### ISSUE TITLE
Påmeldinger

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#211]
**[Original report](https://bitbucket.org/webkom/deprecated-nablaweb/issue/211) by Anders Christiansen Sørby (Bitbucket: [557058:ae644fc6-c029-4950-b4fa-a6dba3ae6156](https://bitbucket.org/557058:ae644fc6-c029-4950-b4fa-a6dba3ae6156), ).**

----------------------------------------

Påmeldinger på kalendersiden viser bare arrangementer. Den burde også vise påmeldte bedpresser.

**Comment by alexarntzen** [comment]
Dette funker nå, så lukker denne
