### ISSUE TITLE
Lag prokomside

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#241]
**[Original report](https://bitbucket.org/webkom/deprecated-nablaweb/issue/241) by Anders Christiansen Sørby (Bitbucket: [557058:ae644fc6-c029-4950-b4fa-a6dba3ae6156](https://bitbucket.org/557058:ae644fc6-c029-4950-b4fa-a6dba3ae6156), ).**

----------------------------------------

Legg prokom inn i menyen og vis en oversikt over alle videoer.

Dette kan løses med flatsider, men kan også gjøres litt mer fancy.

**Comment by alexarntzen** [comment]
Her har det ikke skjedd noe på 2 år. Regner med at prokom tar kontakt hvis de vil ha mer plass på nettsien
