### ISSUE TITLE
Quiz-highscore er treig og ikke sortert

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#260]
**[Original report](https://bitbucket.org/webkom/deprecated-nablaweb/issue/260) by Kristoffer Engedal  Andreassen (Bitbucket: [557058:d9307609-126a-437e-8c95-00fe0ac98710](https://bitbucket.org/557058:d9307609-126a-437e-8c95-00fe0ac98710), GitHub: [kristoea](https://github.com/kristoea)).**

----------------------------------------

Hvis du ser i templaten gjør den en god del function-calls og henter relaterte objekter. så den er ganske treig. Skjønner ikke hvorfor f.eks. score ikke blir brukt. Listen skal jo egentlig være sortert etter score, men det er ikke fysmat-supertrivia for en eller annen grunn? Tror ikke score har blitt lagret, selv om den skal det når objektene lagres. Mye rart her.

Når man går inn på detaljesiden til et reply får man også vite fastien, selv om jeg tror man egentlig kun skal se hva brukeren svarte. Dette burde vel også fikses.

**Comment by ggjersund** [comment]
Skal se om jeg får nøstet opp i Quiz etter å ha sett på Dockerizing. Er det noen som vet om andre apps som bruker ting fra interactive appen?

**Comment by kaprests** [comment]
This was fixed by Amund some time ago. :)
