### ISSUE TITLE
Ikke-publiserte arrangement kommer opp på forsiden

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#267]
**[Original report](https://bitbucket.org/webkom/deprecated-nablaweb/issue/267) by Andreas Bolstad (Bitbucket: [557058:e5d450e7-1579-46d1-92aa-c211ced25452](https://bitbucket.org/557058:e5d450e7-1579-46d1-92aa-c211ced25452), ).**

----------------------------------------

På forsiden er det en liste med arrangement. Per nå har lister den arrangement som har fastsatt dato, men ikke er publisert. Ikke-publiserte arrangement skal ikke vises.

**Comment by ggjersund** [comment]
Dette burde være en easy fix med å legge til en publisert checkbox i modellen for events (sånn umiddelbart ser det ikke ut som det er noen slik field fra før av), sikkert fint for noen som vil få litt innsikt i models og migrations?

**Comment by kaprests** [comment]
Ja enig, hva menes egentlig med et ikke-publisert arrangement?

**Comment by Northo** [comment]
Kanskje det blandes mellom å events og forsidenyheter? Alstå ikke-publisert event = event uten forsidenyhet
