### ISSUE TITLE
Arrangementer som liste hovedsakelig og kalender i tillegg

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#270]
**[Original report](https://bitbucket.org/webkom/deprecated-nablaweb/issue/270) by Andreas Bolstad (Bitbucket: [557058:e5d450e7-1579-46d1-92aa-c211ced25452](https://bitbucket.org/557058:e5d450e7-1579-46d1-92aa-c211ced25452), ).**

----------------------------------------

Kalenderen er veldig uoversiktlig med tanke på arrangement langt i fremtiden. Det er derfor bedre med en liste over alle framtidige arrangement med dato først og fremst, også kan man ha kalenderen som et tillegg (link, mindre versjon enn nå, evt. under arrangement-listen)

**Comment by alexarntzen** [comment]
Nå har vi fått ny kalender, denne er utdatert
