### ISSUE TITLE
Bedre texteditor på admin (WYSIWYG)

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#290]
**[Original report](https://bitbucket.org/webkom/deprecated-nablaweb/issue/290) by Thorvald Molthe Ballestad (Bitbucket: [557058:2eb80dcf-06eb-45e0-8e25-8cf6d5901684](https://bitbucket.org/557058:2eb80dcf-06eb-45e0-8e25-8cf6d5901684), GitHub: [northo](https://github.com/northo)).**

----------------------------------------

Det er krunglete å bruke markdown-editro for ikke-WebKommere. Burde få samme teksteditor som på revysiden.

**Comment by Northo** [comment]
@martehoiskar jobbet på denne. Er det #wontfix?

**Comment by kaprests** [comment]
Tja, for min del så må noen gjerne fikse

**Comment by ulrikbd** [comment]
Implemented ckeditor
