### ISSUE TITLE
Frist og forsvinner trenger ikke være to felter i annonser

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#296]
**[Original report](https://bitbucket.org/webkom/deprecated-nablaweb/issue/296) by Thorvald Molthe Ballestad (Bitbucket: [557058:2eb80dcf-06eb-45e0-8e25-8cf6d5901684](https://bitbucket.org/557058:2eb80dcf-06eb-45e0-8e25-8cf6d5901684), GitHub: [northo](https://github.com/northo)).**

----------------------------------------

Når man legger ut en annonse må man fylle ut både frist og forsvinner. Disse to feltene er ifølge BN nesten alltid samme.

**Comment by foggha** [comment]
Frist bør være et alternativ som ikke er påkrevd da der ikke nødvendigvis er en frist. @AnderBomb og jeg la til at alle stillingsannonser hvor fristen har gått ut har [Utløpt] i tittel.
