### ISSUE TITLE
Seed respekterer ikke unique i groups

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#301]
**[Original report](https://bitbucket.org/webkom/deprecated-nablaweb/issue/301) by Thorvald Molthe Ballestad (Bitbucket: [557058:2eb80dcf-06eb-45e0-8e25-8cf6d5901684](https://bitbucket.org/557058:2eb80dcf-06eb-45e0-8e25-8cf6d5901684), GitHub: [northo](https://github.com/northo)).**

----------------------------------------

Noen ganger lager seed groups med ikke-unike navn

**Comment by ggjersund** [comment]
Quickfix som også kan være fin for nye utviklere. Sjekk ut `nablapps/core/management/commands/seed.py` og linje 85. Bytt til å bruke modellen sin `save()` funksjon + feilhåndtering (integrity error) eventuelt sjekk om gruppen allerede eksisterer før `create()`

**Comment by ggjersund** [comment]
Fikset kjapt med å legge til unique integer i gruppenavnet. Naiv løsning, men fungerer fint for seed. Ellers har jeg også lagt til åpen påmelding for Events i seeden.
