### ISSUE TITLE
Det er lite intuitivt hva 'slug' er i admin-panelet til event, burde ha help_text

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#305]
**[Original report](https://bitbucket.org/webkom/deprecated-nablaweb/issue/305) by Thorvald Molthe Ballestad (Bitbucket: [557058:2eb80dcf-06eb-45e0-8e25-8cf6d5901684](https://bitbucket.org/557058:2eb80dcf-06eb-45e0-8e25-8cf6d5901684), GitHub: [northo](https://github.com/northo)).**

----------------------------------------

**Fint første prosjekt**
I admin panelet til event er det et felt som heter slug. For ikke-webkommere er det ikke lett å forstå hva man skal skrive her (man trenger ikke skrive noe der hvis man ikke har veldig lyst). Det burde være en hjelpetext som forklarer.

**Comment by ggjersund** [comment]
Holder det å skrive "Streng av alfanumeriske tegn bundet sammen av bindestreker"? Kanskje ikke helt utfyllende, men å skrive ned hele definisjonen blir fort litt mye.
