### ISSUE TITLE
Utbedring av nettsteder-feltet på siden for redigering av flatsider

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#310]
**[Original report](https://bitbucket.org/webkom/deprecated-nablaweb/issue/310) by Jonas B (Bitbucket: [5c742be7622fc65f6f61b302](https://bitbucket.org/5c742be7622fc65f6f61b302), ).**

----------------------------------------

Nettsteder-feltet som er synlig når man redigerer/oppretter en flatside lar brukeren legge til lenker, men ikke fjerne dem. Lenker som er lagt til på en flatside legges til på en felles database for nettsteder, slik at de legges til nye flatsider når de opprettes.

Nettsteder-boksen bør derfor utbedres til å la brukeren legge til og fjerne nye og eksisterende nettsteder.  Alternativt kan den fjernes helt, da funksjonen er svært smal, og potenielt unødvendig.

**Comment by ggjersund** [comment]
Sites burde ikke kunne fjernes. Dette vil gi feil på eksisterende sider (https://docs.djangoproject.com/en/2.2/ref/contrib/sites/). Har laget en django app tidligere for flatpages uten sites, men anbefales å bare ha sites installert. 

Usikker på om det er mulig å disable fieldet og sette default på den i admin. Mulig løsning.

**Comment by ggjersund** [comment]
Commit 4788aa97c268b492ff23beb5b1f995761ab2b629
Fjernet add knappen fra admin panelet i account app adminen.
