### ISSUE TITLE
“Åpen for” på arrangementer

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#315]
**[Original report](https://bitbucket.org/webkom/deprecated-nablaweb/issue/315) by Knut Andre Grytting Prestsveen (Bitbucket: [5aa95faaea0a642a2f6d1951](https://bitbucket.org/5aa95faaea0a642a2f6d1951), GitHub: [kaprests](https://github.com/kaprests)).**

----------------------------------------

‌

Burde stå hvem arrangementer er åpne for, og meld deg på knappen burde kanskje ikke være der om man ikke kan melde seg på.

kanskje gjøre knappen usynlig/grå dersom man ikke kan melde seg på \+ felt som viser hvem som kan melde seg på, og deretter legge til et “merknader om påmelding”-felt der arrkom kan skrive f.eks. “Påmelding for ikke-førsteklasse åpner 2. September”.

**Comment by alexarntzen** [comment]
Dette finnes, så lukker issuen
