### ISSUE TITLE
undo_move_to_protected in nabladet migration will fail if media/nabladet exists from before

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#319]
**[Original report](https://bitbucket.org/webkom/deprecated-nablaweb/issue/319) by Thorvald Molthe Ballestad (Bitbucket: [557058:2eb80dcf-06eb-45e0-8e25-8cf6d5901684](https://bitbucket.org/557058:2eb80dcf-06eb-45e0-8e25-8cf6d5901684), GitHub: [northo](https://github.com/northo)).**

----------------------------------------

`undo_move_to_protected` \( in `nabladet/migrations/0011_protect_nabladet.py`\) fails if `media/nabladet` exists from before. That is because the `move` function from shutil fails if the src is an existing directory.

**Comment by kaprests** [comment]
c1ac5ac fixes this, right @Northo?

**Comment by Northo** [comment]
No. c1ac5ac only fixes `move_to_protected`, `undo_move_to_protected` was not fixed, because it does not really cause any harm, and is potentially a good second or third issue.
