### ISSUE TITLE
Batch opplasting av albumbilder

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#321]
**[Original report](https://bitbucket.org/webkom/deprecated-nablaweb/issue/321) by Knut Andre Grytting Prestsveen (Bitbucket: [5aa95faaea0a642a2f6d1951](https://bitbucket.org/5aa95faaea0a642a2f6d1951), GitHub: [kaprests](https://github.com/kaprests)).**

----------------------------------------

Nå må man laste opp et og et bilde, hadde vært fint om man kunne laste opp flere bilder i en batch, og gjerne med felles bildetekst.

**Comment by ggjersund** [comment]
Sjekk gjerne denne om man vil fikse:
https://docs.djangoproject.com/en/2.2/topics/http/file-uploads/#uploading-multiple-files

**Comment by kaprests** [comment]
Hm jo, eller i alle fall delvis. Synes det hadde vært kult om "Nablamedia"-dropdownen også bare blir en knapp som lenker til en side med div. nablamediating, men beskrivelen i denne issuen passer vel ikke helt lenger nei
