### ISSUE TITLE
Redesign av hovedmenyen

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#325]
**[Original report](https://bitbucket.org/webkom/deprecated-nablaweb/issue/325) by Knut Andre Grytting Prestsveen (Bitbucket: [5aa95faaea0a642a2f6d1951](https://bitbucket.org/5aa95faaea0a642a2f6d1951), GitHub: [kaprests](https://github.com/kaprests)).**

----------------------------------------

Vi har snakket om å prøve å få folk til å bruke resten av siden mer, altså ikke bare forsiden.

Dette kan gjøres ved at det enten er mindre som vises på forsiden og/eller at man gjør det mer intuitivt og naturlig å navigere til de andre stedene på nettsiden, og derfor bør nok hovedmenyen endres.

Generelt bør nok vi nok ha færre ting i hovedmenyen og gjøre den litt enklere. Jeg er personlig ganske fan av hvordan Abakus har gjort dette, når en trykker på “om abakus“ så tas en rett til en egen side med “om”-ting, som har sin egen navigasjonmeny. Om vi kan gjøre noe som dette for flere ting i toppmenyen så slipper vi å ha så overfylte lister i toppmenyen som er vanskelig å finne fram i.

**Comment by ggjersund** [comment]
@kaprests Status på denne? Ble ikke menyen fikset nettopp?

**Comment by kaprests** [comment]
Hm jo, eller i alle fall delvis. Synes det hadde vært kult om "Nablamedia"-dropdownen også bare blir en knapp som lenker til en side med div. nablamediating, men beskrivelen i denne issuen passer vel ikke helt lenger nei
