### ISSUE TITLE
cross site scripting

### ISSUE THREAD

**Issue by EirikJaccheri** [Nabla-NTNU/nablaweb#333]
Cite clearly vulnerable to Non-persistent cross site scripting

**Comment by Northo** [comment]
Thank you for your interest in the security of our webpage, Mr. Jaccheri. We are aware of this vulnerability, and are working to fix it.

**Comment by kaprests** [comment]
40ebcdd5f3b95a4f3e2609e39c7f6619447e1798 fixes this.
