### ISSUE TITLE
Løpeklubbens "orientering"

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#335]
Jonas vil lage dette.

**Comment by Northo** [comment]
Hva er dette?

**Comment by jonasbue** [comment]
It's gonna be a beautiful thing*

*I et parallelt univers hvor jeg kommer på webkommøter

**Comment by kaprests** [comment]
Tror det var ment til bruk som bl.a. ting som julekalender, og er på en måte løpeklubben sitt svar på kodegolf. Konseptet er kanskje mer "Amazing race", slik jeg tolket samtalen med løpeklubbleder, bare at det ikke nødvendigvis er "race".
