### ISSUE TITLE
Bli mer delevennlig med mer meta-info

### ISSUE THREAD

**Issue by kristoea** [Nabla-NTNU/nablaweb#339]
Når man linker til Nabla.no fra f.eks. Facebook og Slack så henter sidene bilde, tittel og beskrivelse for å vise hva som linken inneholder. Dette gjøres via meta-tagene i headeren til sidene, og det er det ganske varierende i hvilken grad dette er implementert. I julekalenderen har jeg f.eks. lagt til et eget bilde til deling via `<meta property="og:image" content="https://nabla.no/media/jul_2016_meta.jpg">`, men dette mangler de fleste andre steder. Derfor mangler de fleste linkene fra fb-gruppen (https://www.facebook.com/groups/2248934869/) bilder og linkene blir ganske stygge. Så jeg tenker man burde ha et basis-bilde i `base.html` som man kan skrive over i f.eks. arrangementer med mer relevante bilder. Dette burde være ganske greit å gjøre.

Facebook dokumenterer dette ganske bra her: https://developers.facebook.com/docs/sharing/webmasters/

**Comment by kristoea** [comment]
Denne er veldig nyttig: https://developers.facebook.com/tools/debug/sharing/

**Comment by Northo** [comment]
Dette høres veldig lurt ut, ja. Har hørt fra dem som legger ut på Facebook
at det er veldig varierende hvordan det ender opp med å se ut.
