### ISSUE TITLE
Liste med arrangementer og bedpreser på forsiden blir for stor dersom det er mange tingi "kontoret denne uka"

### ISSUE THREAD

**Issue by Northo** [Nabla-NTNU/nablaweb#342]
Dersom det er mange ting i "Kontoret denne uka" blir grid tracket som listen med arrangementer og bedpreser veldig høyt. Dette gjør at boksen med arrangement ser rar ut, da det blir mye tomrom.

Forslag: ikke la boksen stretche til gridet

**Comment by kaprests** [comment]
Men tror du det er penere om det bare er hvitt tomrom under arrangementboksen?

**Comment by kaprests** [comment]
@Northo

**Comment by kaprests** [comment]
En annen mulig løsning er at Office Calendar kun viser inntil et maks antall hendelser, også blir paginert og får en knapp man kan bla seg videre med. Tenker forøvrig at den ikke trenger å vise events som har vært, og at den heller kanskje kan vise dagen i dag og fremover. Da bør isåfall overskriften heller være "kontoret framover" eller noe sånt.

**Comment by Northo** [comment]
Høres ut som en god løsning

**Comment by Northo** [comment]
![image](https://user-images.githubusercontent.com/7114880/98847384-768f0480-2450-11eb-837f-d0a57b48bd69.png)
