### ISSUE TITLE
Oversiktsside over bedriftspresentasjoner

### ISSUE THREAD

**Issue by jonasbue** [Nabla-NTNU/nablaweb#345]
Bedkom ønsker en side som inneholder en oversikt over kommende bedriftspresentasjoner, med litt info og lenker til arrangementene.

**Comment by kaprests** [comment]
@Northo du jobber jo for tiden med en sånn side for arrangmenet, så jeg vil tro at dette løses når de endringene er på plass.

**Comment by Northo** [comment]
Ja, tenker det
