### ISSUE TITLE
Ikke-sentrert undergruppe-side

### ISSUE THREAD

**Issue by frederni** [Nabla-NTNU/nablaweb#346]
hei pc-folk,
oppdaget når jeg gikk inn på komiteer-siden, https://nabla.no/komite/komiteer, at rutenettet av logoer og sånn ikke var sentrert, se [bilde her](https://i.imgur.com/pXN3WMG.png)

**Comment by Northo** [comment]
Dette var rart. Hvilken telefon og browser bruker du?

**Comment by Northo** [comment]
Takk for god oppfølging av siden! Det hjelper masse

**Comment by kaprests** [comment]
Ja, takk for tilbakemelding. Blir ikke sånn på min telefon, der sentrerer den, men av en eller annen grunn så laster den inn siden litt zoomet inn.

**Comment by kaprests** [comment]
Er sikkert noe litt jalla i CSS-en :upside_down_face:

**Comment by fleroviums** [comment]
Til info var det på Chrome for iOS hehe

**Comment by Northo** [comment]
@kaprests lurer på om det har noe med width på grid. Ble satt litt på måfå
