### ISSUE TITLE
Gammel Slack-logo i footer

### ISSUE THREAD

**Issue by fleroviums** [Nabla-NTNU/nablaweb#347]
Det er den gamle Slack-logoen i footer, se vedlagt bilde.
Kan ikke sånn web ting men vet at [fontawesome ](https://fontawesome.com/icons?d=gallery&q=slack)har den nye slack-logoen hvis det er de dere bruker:))
![gammel-vs-ny-logo](https://user-images.githubusercontent.com/23258333/66845745-e3477f00-ef70-11e9-8acd-639f0a1ba63e.jpg)

**Comment by kaprests** [comment]
Takk for headsup! Ganske sikker på at det er fontawsome vi bruker

**Comment by Northo** [comment]
Det er font awesome som ikke har oppdatert Slack logoen i vår versjon. Planen er vel å oppdatere fa snart.

**Comment by amunso** [comment]
Resolved by 5326a9a5a7eb223bc7ae1efe0f19ff0324d3e7cc
