### ISSUE TITLE
Sponsor logos on front page overflows horizontally

### ISSUE THREAD

**Issue by Northo** [Nabla-NTNU/nablaweb#348]
The sponsor logos are aligned horizontally. If the window is sufficiently narrow, the logos overflows and are not visible.

Should either scale or stack under each other on smaller screens.
![Screenshot_2019-10-15 Nabla - linjeforeningen for Fysikk og matematikk ved NTNU](https://user-images.githubusercontent.com/7114880/66850679-91efbd80-ef79-11e9-9e38-54d9814115d2.png)

**Comment by alexarntzen** [comment]
I fix

**Comment by alexarntzen** [comment]
Skal være fikset nå
