### ISSUE TITLE
Nabla-logoer på nettsiden

### ISSUE THREAD

**Issue by alexaoh** [Nabla-NTNU/nablaweb#351]
Får tilbakemelding om at mange av Nabla-logoene på nettsiden er forskjellige. For eksempel på undergruppe-siden. Prokom jobber med logoene tror jeg.

**Comment by kristoea** [comment]
Ja ser at noe har skjedd her. De fleste av logoene på https://nabla.no/komite/komiteer er fra 2016-ish da Webkom lagde logoer til alle komiteene og fikk dem alle godkjent. De ligger i drive i i svg format (https://drive.google.com/drive/folders/0ByXp48y8-QVFYTE4bmQzNC1oSFE), ble lastet opp i NablaGroup-instansene og kan sees f.eks. her https://nabla.no/brukere/view/. Men nå seer jeg at de også har blitt lastet opp i ComPage-instansene og brukes i oversikten her https://nabla.no/komite/komiteer. Dette var planen hele tiden (se #253 som nå egentlig er "løst"), men planen var å slå sammen ComPage og NablaGroup først. Se #259, som jeg enda har dårlig samvittighet for at jeg ikke har fikset... Se https://bitbucket.org/webkom/gruppe-test/src/master/ for noe jeg halvveis kom i gang med.
