### ISSUE TITLE
CodeGolf models not imported in `interactive.models`

### ISSUE THREAD

**Issue by Northo** [Nabla-NTNU/nablaweb#354]
Interactive has its models saved in a directory, `nablapps/interactive/models`. This directory contains a file `__init__.py`, which has to include `models/code_golf.py` in order for code golf models to be imported when using the module path `nablapps.interactive.models`. Now one has to use `nablapps.interactive.models.code_golf`.

**Comment by kaprests** [comment]
0457bdca1a36875254879b5430a0d3f13fa12650 resolves this.
