### ISSUE TITLE
Oppmeldingsystem til undergrupper på nettsiden

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#361]
Styrets visjon:
- Prioritert søknadsliste
- Mulighet for å velge å være anonym
- Disclaimer om man bare søker én ting
- Fritekstfelt hvor man kan spesifisere ønsket stilling, instrument etc.
- Ikke-anonyme søkere listes i en slags tabell
- Totalt antallsøkere til hver gruppe vises også i tabellen et sted
- Anonyme kan enten listes i tabellen som “anonym” eller utelates fra tabellen

**Comment by kaprests** [comment]
Du er vel ferdig med dette @Northo, sånn at issuet kan lukkes?

**Comment by Northo** [comment]
Er vel forsåvidt det...

**Comment by Northo** [comment]
Så flink du er som rydder i issues

**Comment by kaprests** [comment]
Haha, ikke noen systematisk rydd, bare plukket litt på toppen av lista
