### ISSUE TITLE
Bedre nablashop

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#370]
Forslag fra økonomiansvarlig til forbedringer av Nablashop.

-Kanskje det hadde vært mulig å ha en egen knapp for Nablashop ("fa-shopping-cart" i navbar e.l.
-Fylle handlekurv og sende inn "bestilling"
-Ha kontrol på lagerbeholdning

Per i dag er den bare en statisk flatside

**Comment by alexarntzen** [comment]
Holder du på med denne @yawarm?
