### ISSUE TITLE
Andre side på bildealbum returnerer 404

### ISSUE THREAD

**Issue by frederni** [Nabla-NTNU/nablaweb#371]
Heia!
På bildealbum er det ikke mulig å trykke på "neste ->". Den er linket til https://nabla.no/album/2/ og returnerer 404

**Comment by jonakas** [comment]
4a4b9be

**Comment by frederni** [comment]
@jonakas Det har blitt lagt til nye albumelementer, og ser ut som det dessverre har ført til samme feil som rapportert her 😢

**Comment by jonakas** [comment]
@frederni Var fikset men ble endret av senere commit, 379b6c2
skal fikse dette nå.
