### ISSUE TITLE
Profilbilder under kommentarer er pikselerte

### ISSUE THREAD

**Issue by frederni** [Nabla-NTNU/nablaweb#375]
Bildene til brukere som kommenterer under arrangement o.l. er pikselerte og lowres i forhold til det faktiske bildet. 
Ser slikt ut i kommentarfelt:
![image](https://user-images.githubusercontent.com/23258333/75114657-4e5c3d00-5658-11ea-8075-b0b0586ecc74.png)

På profilene vises derimot bildene i riktig oppløsning:
![image](https://user-images.githubusercontent.com/23258333/75114685-911e1500-5658-11ea-98c4-83ef02db18ca.png)

**Comment by kaprests** [comment]
This is fixed by this commit: ec5f67fd451113448fbaf710a6e3b82be02d67f8
I mistakingly reduced the resolution in a previous commit, thank you for raising this issue! :)
