### ISSUE TITLE
Emoji-posting gir 500

### ISSUE THREAD

**Issue by frederni** [Nabla-NTNU/nablaweb#379]
Dersom man kommenterer emojis i kommentarfelt gir 500-feilmelding.
Virker som det gjelder alle type emojis (❤🍯 osv)

**Comment by alexarntzen** [comment]
Det virker som om MySql ikke bruker vanlig UTF-8 som standard, men utf8mb3. Det kan være å legge til 
`
        'OPTIONS': {
            'charset': 'utf8mb4',  
        }
`
i DATABASES fikser dette, men jeg vet ikke hvordan jeg skal teste dette på en sikker måte.
