### ISSUE TITLE
Style of button on "Varsling og Ressursbank"

### ISSUE THREAD

**Issue by Northo** [Nabla-NTNU/nablaweb#380]
The links/buttons on "Varsling og Ressursbank" looks hideous.
**Issue:** Buttons looks hideous.
**Fix:** Make buttons look gorgeous.

**Recommended solution:**
Now, the `a`-tag is placed within a `button`-tag. This is poor practice. It would be better to use only the `a`-tag, and apply button style to that. Look at https://getbootstrap.com/docs/4.0/components/buttons/, the idea is to give a the appropriate button class.

As a first issue, the hardest part is probably to find the file to be fixed. Hint, look at the template-files.

**Comment by kwillno** [comment]
Removed button-tags in flatsider in adminpage. Now using dark version buttons.

**Comment by Northo** [comment]
Great!
