### ISSUE TITLE
Fargekoordinering mellom arrangementside og forside widget

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#382]
De to arrangementlistene gir arrangement og bedpres hver sin farge, men ikke de samme to fargene. Det hadde vært nice om vi brukte de samme to fargene begge steder.

**Comment by Northo** [comment]
Oppklaring: er altså snakk om listen på forsiden og listen på [nabla.no/arrangement/](https://nabla.no/arrangement/). 

![Screenshot_2020-03-18 Nabla - linjeforeningen for Fysikk og matematikk ved NTNU(1)](https://user-images.githubusercontent.com/7114880/76937431-16fa4c80-68f5-11ea-9077-7b4c611d7b27.png)
![Screenshot_2020-03-18 Nabla - linjeforeningen for Fysikk og matematikk ved NTNU](https://user-images.githubusercontent.com/7114880/76937435-1792e300-68f5-11ea-871d-2f947f23de90.png)

**Comment by alexarntzen** [comment]
Hadde også vært kult å legge til fargevariabler i default.css. Eksempel: https://developer.mozilla.org/en-US/docs/Web/CSS/var
