### ISSUE TITLE
Interwikien liker ikke bootstrap 4

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#383]
Interwikien ser rar ut nå (mer enn til vanlig), antakelig som resultat av oppgraderingen av bootstrap.

**Comment by alexarntzen** [comment]
Wiki med bootstrap4 skal være fikset av commit e7005a35769cc7c0d6328b3e257d0bdb9acc28b6

**Comment by kaprests** [comment]
Nice! Da lukker jeg denne :)
