### ISSUE TITLE
Reklame-app for å håndtere evt. reklame i sidebaren

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#39]
**[Original report](https://bitbucket.org/webkom/deprecated-nablaweb/issue/39) by Trygve Bertelsen Wiig (Bitbucket: [557058:40d383ee-0ff6-4f92-bc40-3e32fccfb33e](https://bitbucket.org/557058:40d383ee-0ff6-4f92-bc40-3e32fccfb33e), ).**

----------------------------------------

Tipper bedrifter som reklamerer i sidebaren gjerne vil ha ting som statistikk over klikk, m.m.

I tillegg er det jo veldig greit med mulighet for å endre på reklamen uten å gå inn og redigere templaten.

**Comment by alexarntzen** [comment]
Vi ble enige om reklamene forrige semester
