### ISSUE TITLE
Engelsk flagg gir 404

### ISSUE THREAD

**Issue by frederni** [Nabla-NTNU/nablaweb#391]
Får beskjed at nettleser ikke finner https://nabla.no/static/img/GB_flag.svg
![image](https://user-images.githubusercontent.com/23258333/79211322-670df580-7e46-11ea-8b03-e670c91f0687.png)

**Comment by kristoea** [comment]
Fikset med `python manage.py collectstatic` som manglet etter 74b008c @pettaroni
