### ISSUE TITLE
Nabla.no på Internet Explorer er broken

### ISSUE THREAD

**Issue by frederni** [Nabla-NTNU/nablaweb#392]
Vet ikke om det er noe vits å patche dette da de eneste som bruker Internet Explorer er 50+, men tenkte å legge det ut likevel. Dette er altså gamle Internet Explorer (iexplore), *ikke Microsoft Edge*.
Kanskje det kan være en idé å gi sånn "updatert browser" popup (hvis det går an) hvis man besøker siden på Internet Explorer. Til info er dette på versjon 11.592.18362.0, Oppdateringsversjon 11.0.170 (KB4534251)

![image](https://user-images.githubusercontent.com/23258333/79211368-78570200-7e46-11ea-9919-02e8fdf5c6ec.png)

**Comment by kristoea** [comment]
Du har nok rett i at det ikke er mye vits i å støtte IE lenger og vi er ikke de eneste (se f.eks. abakus.no med IE). Er nok kun legacy enterprise som burde bry seg om det. En generell løsning kunne basert seg på https://github.com/outdatedbrowser/outdated-browser, virker ganske greit.
