### ISSUE TITLE
Indexer in wikien er bare kaos

### ISSUE THREAD

**Issue by martkjoh** [Nabla-NTNU/nablaweb#393]
Index-listene i wikien er rotete. Antagelig på grunn av oppdatering av bootsrap.

![lister](https://user-images.githubusercontent.com/32961702/80627096-af850000-8a4f-11ea-87d5-faece8c80023.png)

**Comment by martkjoh** [comment]
This goes deeper than i though

**Comment by alexarntzen** [comment]
Ser ut som om dette ser bra ut  nå
<img width="981" alt="Skjermbilde 2020-09-09 kl  18 37 01" src="https://user-images.githubusercontent.com/48533802/92627344-814fe080-f2cb-11ea-975b-7b80d10bcd9a.png">
