### ISSUE TITLE
Forbedre "om nabla" siden

### ISSUE THREAD

**Issue by martkjoh** [Nabla-NTNU/nablaweb#394]
"Om nabla" siden kan forbedres ved sortere linkene som vises på venstre siden. Linkene er av flere forskjellige typer:

 1. Linker til enkeltsider med  informasjon om nabla, som "Generelt om nabla" og styret
 2. Linker til wiki-sider
 3. Linker til andre nabla-apps

Linker av type 1 kan gjøres om til wiki-artikler, noen som også fikser problemet med at mange av disse sidene ser forskjellige ut. Det burde være en tydligere forskjell på linker av type (1 og 2) og 3.

**Comment by alexarntzen** [comment]
Er du ferdig med denne @yawarm?
