### ISSUE TITLE
Old calendar

### ISSUE THREAD

**Issue by kwillno** [Nabla-NTNU/nablaweb#398]
When opening the old calendar from the link in the new calendar I got a 500 error.
URL: https://nabla.no/arrangement/calendar/

Seems to be both mobile and desktop.

**Comment by numfys** [comment]
Flott jobba!

**Comment by Northo** [comment]
Flott jobba!

**Comment by Northo** [comment]
Den gamle kalenderen er ganske jalla. Den kan godt være et (stort) prosjekt for noen som vil gjøre noe litt mer omfattende. Kan gjerne skrives om fra bunn.

**Comment by Amund211** [comment]
Some context for this issue:
```
[amundes@babel nablaweb]$ tail -n 1 /var/log/django/nablaweb/error.log # Show last line of error log
django.urls.exceptions.NoReverseMatch: Reverse for 'event_list page-link' not found. 'event_list page-link' is not a valid view function or pattern name.


[amundes@babel nablaweb]$ grep -r "event_list page-link" # Search for occurances of 'event_list page-link' in the code
nablapps/events/templates/events/event_list.html:        <a href="{% url "event_list page-link" next.year next.month %}">&raquo;</a>
```
The offending line `{% url "event_list page-link" ...` is referring to a url with the reverse-name `event_list page-link`, which does not exist.

The url reverse-names are defined in `urls.py` files, which in this case is [`nablapps/events/urls.py`](https://github.com/Nabla-NTNU/nablaweb/blob/master/nablapps/events/urls.py#L32).
Good luck!
