### ISSUE TITLE
Nabladet .pdf upload is broken for most users

### ISSUE THREAD

**Issue by amunso** [Nabla-NTNU/nablaweb#399]
Nabladet .pdf upload is broken for most users

Known:
- both sfw and nsfw fails to accept .pdf uploads from most users (.png is accpeted from all users)
- sends a 500

Unknown:
- does not seem to be related to browser, filesize, userpermissions

**Comment by kaprests** [comment]
Jeg får ikke til å gjenskape, går fint for meg å laste opp pdf. Har ikke sjekket så nøye, men utifra loggen så er det wand/immagemagick som ikke er helt fornøyd.

`wand.exceptions.PolicyError: attempt to perform an operation not allowed by the security pTolicy 'PDF' @ error/constitute.c/IsCoderAuthorized/409`

**Comment by Northo** [comment]
Dette ble diskutert på Slack, spesifikt det du nevner der, @kaprests. Endte fiksen vi beskrev der med å fungere, @amunso ?

**Comment by kaprests** [comment]
Åja, har koblet litt av slack i ferien. Ut ifra diskusjonen der så ser det jo ut til at det er fiksen fungerte 🤘.

**Comment by amunso** [comment]
Det fungerte @Northo, og ja det er vel på sin plass å lukke issuet @kaprests

**Comment by Northo** [comment]
🤘
