### ISSUE TITLE
Klarer ikke opprette tråd

### ISSUE THREAD

**Issue by kwillno** [Nabla-NTNU/nablaweb#400]
Får ikke laget nye tråder inne i en ny kanal.
Klarer å opprette en kanal, men klarer ikke opprette noe tråd.

Har prøvd i både kullgruppe og i en separat Gruppekanal.

I begge tilfeller får jeg 500

**Comment by jonasbue** [comment]
Har du emojis i den nye tråden? I tittel eller beskrivelse, for eksempel? Jeg tror emojis fremdeles gir 500-feil.

**Comment by kwillno** [comment]
Nei, har ikke det. 
Tror ikke det er relatert til #379 da jeg prøvde med kun ASCII, og det ser ut som problemet der er relatert at UTF-8 ikke brukes.

**Comment by kaprests** [comment]
Tror 9c065378bb fikser dette :) Hadde visst sneket seg inn en bug hvor det ble forsøkt et funksjonskall til en variabel

**Comment by kwillno** [comment]
@kaprests Ser ut til at det fungerer som det skal nå!
