### ISSUE TITLE
Events med påmelding viser forvirrende melding før påmelding åpner

### ISSUE THREAD

**Issue by Northo** [Nabla-NTNU/nablaweb#401]
På Events med påmelding står det "Påmelding kreves" og "Påmelding er stengt" før påmeldingen åpner. 
Dette er forvirrende, siden det høres ut som at påmelding har vært åpen, men nå er stengt.
Burde heller stå noe slikt som "Påmelding har ikke åpnet enda" eller "Påmelding er ikke åpen".

**Comment by kaprests** [comment]
Godt poeng :)
