### ISSUE TITLE
Profilbilder kolliderer med tabell når width=ca 990px

### ISSUE THREAD

**Issue by frederni** [Nabla-NTNU/nablaweb#404]
Med ca. 770-990px bredde på nettleseren kolliderer profilbildet inn i teksten på brukerprofiler. Gjelder ikke de fleste mobiler (i hvert fall ikke min), så problemet er ikke særlig omfattende. Se bildet under

![image](https://user-images.githubusercontent.com/23258333/90890038-8222e000-e3b9-11ea-9561-cd1cfc9e71b4.png)

**Comment by alexarntzen** [comment]
Ser ut som om dette ble fikset i pull request #407, der minste bredde på `content` ble økt
