### ISSUE TITLE
Add to Google Calendar button does not work when event does not have a end-time

### ISSUE THREAD

**Issue by Northo** [Nabla-NTNU/nablaweb#416]
Events has a button that allows you to add an event to your google calendar, see the button under the info-bar.
This is really just a link to google calendar's add event page, with some pre-filled values.
Apparently, when there is no end date, this fails.
See for example the event https://nabla.no/arrangement/1384-bedriftspresentasjon-med-accenture.

Specifically, in the url there is one parameter `dates` with value like `20201009T173000/20200109T174000`, which means September 10. from 1730 to 1740. If you are unsure what parameter in url means, look up GET parameter.

One suggested fix is to simply set some end date for events without end date.

**Comment by Amund211** [comment]
Whoops, fixed by 4a7990c.
