### ISSUE TITLE
Revy.nabla.no design choices

### ISSUE THREAD

**Issue by amunso** [Nabla-NTNU/nablaweb#418]
Ref old notification from "Jenny"
1. ~~Akkurat nå har vi (jeg og Lise) ikke tilgang til å redigere teksten på “Om oss”-siden, det hadde vært veldig greit å få!~~
2. Nederst på “Om oss”-siden kan man se hvilke undergrupper vi har, men når vi skal ha opptak til noe annet enn de vanlige undergruppene (eller ikke alle undergruppene) så må man fjerne at de er publisert også på “Om oss”-siden. Er det noen måte rundt dette sånn at man til en hver tid kan ha alle undergruppene på “Om oss”-siden?
3. På forsiden på under “Siste nytt” og når man trykker seg inn for å se flere nyheter så er nyhetene sortert med eldste innlegg først, kan det endres til at det nyeste innlegget er først?
4. Inne på arkiv tror jeg arkivene er sortert med siste arkiv først..? Litt usikker, men her hadde det vært fint om det ble sortert i alfabetisk rekkefølge!
5. Bildekarusellen på forsiden sorterer også bildene etter hva som ble lastet opp først, altså eldste bilde først, veldig fint om det også er motsatt.

**Comment by amunso** [comment]
-snu listene av produksjoner under arkiv på revy.nabla.no
-Rekkefølge av elementer i om-oss; liten ingress, liste av undergrupper
-forklaring over hver revy etter du har trykket på en revy i arkiv
-revyens forskrifter som pdf under om-oss

**Comment by kaprests** [comment]
Jeg lukker denne jeg @amunso, siden det gjelder revysiden som er en egen side. Revysiden ligger vel forøvrig igjen på bitbucket og burde vel flyttes hit. Kan se for meg at det kanskje er litt pakker og sånn som burde oppdateres på den, så kanskje det bør være en sak på møtet neste uke.
