### ISSUE TITLE
Kalender

### ISSUE THREAD

**Issue by emmasorset** [Nabla-NTNU/nablaweb#419]
Den nye kalenderen er mye finerer enn den gamle, men jeg savner en enkel måte å bla frem og tilbake mellom månedene på:) det som også var fint med den gamle var at man ser alle dagene, men skjønner at man ikke kan få alt

**Comment by kaprests** [comment]
Enig i at den gamle kalenderen kan ha noen fordeler over den nye, og det er vel grunnen til at vi ikke fjernet den :) Hvis du trykker på "Ta meg til den gamle kalenderen" så kommer du til den gamle.

Skjønner at linken til den gamle kanskje forsvinner litt, og jeg tror planen på sikt er å gjøre det mer intuitivt å skifte mellom å se arrangementene i liste og kalender.
