### ISSUE TITLE
Lister

### ISSUE THREAD

**Issue by emmasorset** [Nabla-NTNU/nablaweb#425]
Kan alle lister med navn enten sorteres på fornavn eller etternavn, nå er det litt av begge deler (for eksempel er prikk-registreringen sortert på fornavn imens listen over påmeldte er sortert på etternavn) <3<3, evt en knapp(noe) så man kan velge om listen skal være organsiert etter fornavn, etternavn eller påmeldingsrekkefølge

**Comment by alexarntzen** [comment]
Sorterte etter etternavn i arrangement nå. Hvis du vil ha noe mer så er det bare å si ifra ☔️
