### ISSUE TITLE
Unable to add link in body text

### ISSUE THREAD

**Issue by Northo** [Nabla-NTNU/nablaweb#429]
After adding rich text editor (which is awesome) in   e8a1e12, it seems like we are unable to add links. I suppose this is because the editor does not allow HTML or Markdown. Or maybe the markdown tag is removed in templates.

We should add the ability to create links.
Would also be nice if it is possible to edit the "raw" text, for special cases.

**Comment by ulrikbd** [comment]
La til funksjonalitet for å legge til lenker manuelt nå. Bør kanskje tillate begge deler, men er en midlertidig fix.
