### ISSUE TITLE
Change image and link in /stillinger

### ISSUE THREAD

**Issue by alexaoh** [Nabla-NTNU/nablaweb#430]
Students as Partners - Studentforskning i Fysikk is changing its name to Prosjekt Schrodinger. Therefore it has a new domain name (home.phys.ntnu.no/ps) and a new banner/poster. 
Would like if you could update to the new url and replace the old image with the new one. It is in the sidebar in /stillinger. The new image is attached below.
![ps](https://user-images.githubusercontent.com/47002854/96874484-71a0eb80-1476-11eb-9003-14dcac1fc8cd.png)

**Comment by Yashs911** [comment]
Hi @alexaoh I would like to work on this issue.

**Comment by alexarntzen** [comment]
Go ahead. Submit a pull request when you are ready 👍

**Comment by Yashs911** [comment]
@alexarntzen I tried searching for the file but couldn't find it can you please help me out.

**Comment by alexarntzen** [comment]
Upon reviewing this its clear you do not have access to change pictures that are not stored on GitHub. So I updated the image. 

Feel free to try any other issue @Yashs911 .
