### ISSUE TITLE
Add link to company webpage in job advertisement

### ISSUE THREAD

**Issue by Northo** [Nabla-NTNU/nablaweb#449]
On job advertisements there is a link to the company web page in the meta side bar on the right.
However, it would be nice if the logo/image also was a link, as it is much more of a visual element than the link on the right.

**Comment by lovisesk** [comment]
845e00ecbcc61b32ba fixes this

**Comment by lovisesk** [comment]
Når man trykker på bildet kommer man til bedriftens hovednettside, ikke spesifikt nettside med søknad o.l. til denne stillingen.

**Comment by lovisesk** [comment]
A previous fix messed this one up, but now it works again.
Commit: 014bcf23d7614d9b28776da6f19e29353ac74860 fixes this
https://github.com/Nabla-NTNU/nablaweb/pull/547
