### ISSUE TITLE
Sangtekster

### ISSUE THREAD

**Issue by emmasorset** [Nabla-NTNU/nablaweb#456]
Hei:) har prøvd å legge ut sangtekstene til NWA, men de kommer ikke opp noe sted jeg finner på nettsiden, hvordan kan jeg egt gjøre det? evt kan dere fikse?

**Comment by kaprests** [comment]
Hei, beklager litt sen respons. Hvor forsøkte du å legge tekstene? Kan det passe å ha dem f.eks. på internwikien?

**Comment by emmasorset** [comment]
Prøvde å legge dem på internwikien der vi har litt sangtekster, den som heter «sanger» synes internwikien er et fint sted å ha dem

Sendt fra min iPhone

20. mar. 2021 kl. 14:27 skrev Knut Andre Grytting Prestsveen ***@***.***>:

﻿

Hei, beklager litt sen respons. Hvor forsøkte du å legge tekstene? Kan det passe å ha dem f.eks. på internwikien?
