### ISSUE TITLE
Lenkefeil i siden til Styret

### ISSUE THREAD

**Issue by yawarm** [Nabla-NTNU/nablaweb#466]
Liten lenkefeil på siden til styret: https://nabla.no/komite/om/styret/
![image](https://user-images.githubusercontent.com/71782750/112352934-83a7e400-8ccb-11eb-96fa-3d26c3c68922.png)
Ville ha vært fint om dette kunne fikses :)

**Comment by frederni** [comment]
Fixed via Admin:)
