### ISSUE TITLE
Skifte fargen til Navbaren

### ISSUE THREAD

**Issue by yawarm** [Nabla-NTNU/nablaweb#467]
Som vi ble enige om møtet 17.03.21 - skal vi bytte fargen til navbaren til blå - slik som på Nablas fane. 
Selve skriften på navbaren skal være gull - slik som på Nablas fane.

**Comment by yawarm** [comment]
Denne var ikke så altfor lett

**Comment by kaprests** [comment]
Tips: sjekk ut static/css/default.css :slightly_smiling_face:
