### ISSUE TITLE
Legg til informerende tekst om kodegolf

### ISSUE THREAD

**Issue by yawarm** [Nabla-NTNU/nablaweb#478]
Innenfor programmering finnes det mange ulike "sportsgrener". Noen handler om å løse en oppgave på kortest mulig tid, det vil si tiden det tar å skrive et fungerende program. Andre om å løse en oppgave på kortest mulig kjøretid, det vil si tiden programmet bruker på å løse oppgaven. En tredje kategori handler om å løse en oppgave på færrest mulig tegn; kodegolfing. Ordet kommer av at man i golf forsøker å komme seg rundt banen på færrest mulig slag.

Teksten legges inn her:
![image](https://user-images.githubusercontent.com/71782750/114946892-583c9300-9e4c-11eb-9e6b-06cee32d5216.png)

**Comment by frederni** [comment]
Fixed in d995e64d90dfae1777f091fafce47ba11104a5e3
