### ISSUE TITLE
Bedpres and event links on front page should lead to page with only that type of events

### ISSUE THREAD

**Issue by Northo** [Nabla-NTNU/nablaweb#507]
When clicking "Arrangementer" or "Bedriftspresentasjoner" on the front page, the user is taken to the event list page. However, all types of events are shown, not only the type the user pressed.

You can decide yourself what is the best behaviour, but I believe that at least bedpres should lead to only bedpres. If event should lead to only events or also bedpres, is up to you.

**Comment by Joliv3r** [comment]
fixed #519
