### ISSUE TITLE
Automatic payment confirmation using Vipps

### ISSUE THREAD

**Issue by Northo** [Nabla-NTNU/nablaweb#509]
We tried several years ago to make a system where payments would be automatically registered using a transaction list from DNB, with a custom KID number solution. However, getting such a list on a usable format from DNB was not easy, so we abandoned the project.

However, now many use Vipps to pay for events. Could it be that Vipps has a better solution for exporting lists??

In that case, a nice solution could be to have nablaweb give the user some string they had to type in to the Vipps transaction. Then, okonomiansvarlig could export the list from Vipps, feed it into nablaweb, and we could use the string as a reference for registering who payed.

**Comment by yawarm** [comment]
First, I want to start by doing inventory counting digitally.
There will be an overview of all the items and the number that are in store.
When you buy, you will have the opportunity to tick off what you have bought and how much you have bought of that item. Then the "count" of the items will be updated digitally.

After this is in place, the payment system itself will be implemented. Where the user pays using Vipps.

**Comment by yawarm** [comment]
We have now chosen to solve this problem in a slightly different way.
Has introduced something called NablaCoin, which will be used to do all purchases through the website. Then I merge BeerOffice with Nablashop. I have also added all the functionality I mentioned in the previous comment.
