### ISSUE TITLE
Add infographic of student card in the form where one enters the EM card number

### ISSUE THREAD

**Issue by Northo** [Nabla-NTNU/nablaweb#527]
People are confused as to which number they should add in https://nabla.no/brukere/edit/. We could add an infographic like this: 
![studentCard](https://user-images.githubusercontent.com/7114880/135515820-6d0f0fc7-ca65-471e-8cbe-f1f7972c2bf3.png)
[studentCard.zip](https://github.com/Nabla-NTNU/nablaweb/files/7261917/studentCard.zip)
(inkscape file in zip if you want to alter it)

**Comment by alexarntzen** [comment]
Somebody forgot to ``collectstatic``, but it totally works now
