### ISSUE TITLE
Oppdatering av forsiden

### ISSUE THREAD

**Issue by yawarm** [Nabla-NTNU/nablaweb#546]
Etter mange tilbakemeldinger om at nettsiden er uoversiktlig, har vi kommet frem til at en liknende løsning hadde vært nice. Denne løsningen er tatt fra Online, og jeg føler at en slik løsning på nettsiden er bra. 
![image](https://user-images.githubusercontent.com/71782750/138328340-226d4b2b-72f0-4baa-840f-77fa9a473946.png)
Fordelen med en slik løsning er at man kan legge fokus på flere arrangementer samtidig. Det gjør også nettsiden mer enklere å bruke, ettersom man ikke trenger å bla altfor langt ned på siden. 

Som diskutert i møtet, ønsker vi å implementere en sånn løsning

**Comment by alexarntzen** [comment]
Fixed with  by  commit 1e1361a
