### ISSUE TITLE
Hjelpetekst i django admin for spill

### ISSUE THREAD

**Issue by Amund211** [Nabla-NTNU/nablaweb#556]
I admin interfacet for spill (https://nabla.no/admin/interactive/game/) eller (http://localhost:8000/admin/interactive/game/) må man legge til en lenke til spillet. Denne lenken må være relativ, ettersom den settes sammen med url-en vår. Altså: hvis man vil lenke til `https://nabla.no/kodegolf/` må man skrive inn `kodegolf/`. Dersom man legger inn hele lenken vil man få `https://nabla.no/https://nabla.no/kodegolf/` og det vil ikke fungere.

En fin måte å fikse dette på kan være å legge til [help text](https://docs.djangoproject.com/en/3.2/ref/models/fields/#help-text) til url-feltet på spill modellen.

**Comment by lovisesk** [comment]
7ab38430e69be7a7bf3e84b1547a3d0ff88f9802
Pretty sure (though not completely) this commit adds this, but as it failed every python-test, i got cold feet even though i've heard that there are issues with the tests now.
Therefore I redid what I had done and made it the way it had been before. Now I know how I did it though, so it should be an easy fix if this actually was correct

**Comment by lovisesk** [comment]
b16ac63793123c5ea8e3e16becdeb7bbd0be619d
This commit now adds the helptext
