### ISSUE TITLE
New design of front page

### ISSUE THREAD

**Issue by yawarm** [Nabla-NTNU/nablaweb#559]
We have long discussed updating the design of the front page. Here is a suggestion which had great support. 
![nablaweb](https://user-images.githubusercontent.com/71782750/142493982-4ad25735-544f-495c-8184-56ec17ff4b00.png)

A bit more info about the figure:
Nablalogo:
    Lenke til forsiden
Kalender:
    Lenke til events
Stillingsannonser:
    Lenke til stillingsannonser
Nablamedia:
    Dropdown eller lenke til samleside for media
Om Nabla:
    Enten dropdown eller bare lenke til om-side med egen meny
    (jeg foretrekker å droppe dropdown, men ikke så nøye
Intern:
    Lenke til side for interne, som også må lages.
    helst ikke dropdown

    Internsiden:
        Samleside for ting som krever innlogging:
            -nabla.no/stem
            -polls
            -nablashop
            -saldo officebeer?
            -Kanskje spill?
            -osv.
        Lenkene fra "diverse" kan sikkert også ligge her

    Jeg synes at "Handlevogn" kun skal være synlig på internsider, 
    eller (kanskje helst) bare i nablashop. 

Any thoughts @alexarntzen?

**Comment by alexarntzen** [comment]
Collection of news as seperate card and the "Intern" button looks nice

**Comment by alexarntzen** [comment]
Jeg tror internside kan være en god ide!

**Comment by alexarntzen** [comment]
Lager en issue på det internside i stedet, tror denne issuen blir litt for generell
