### ISSUE TITLE
Advent calendar posts on Facebook previews Accenture logo

### ISSUE THREAD

**Issue by frederni** [Nabla-NTNU/nablaweb#562]
Currently, sharing the advent calendar to Facebook results in the big accenture logo as preview: 
![image](https://user-images.githubusercontent.com/23258333/145555876-fbb33ae5-1170-4a6a-9353-85b87223b135.png)

Should be fixed by adding `<meta property="og:image" content="X" />` (X being the preview image we want) in the head of `nablapps/interactive/templates/interactive/advent_base_2021.html`.

**Comment by kaprests** [comment]
> Why is the Accenture logo there? Are they a sponsor of the calendar?
> 

yes, they sponsored the last calendar (2021), but they are not generally a sponsor.
