### ISSUE TITLE
Text overflow in /arrangement

### ISSUE THREAD

**Issue by alexarntzen** [Nabla-NTNU/nablaweb#577]
Text overflow of "Bedpres" in /arrangement on mobile:
![Screen Shot 2022-02-01 at 14 25 57](https://user-images.githubusercontent.com/48533802/151976808-e9881229-441e-413d-9eeb-bc6da8b47dea.png)

**Comment by Famara72** [comment]
Bedpres forsvinner nå når bredden er mindre enn 575px.
