### ISSUE TITLE
Wrong status on arrangement/mine/

### ISSUE THREAD

**Issue by alexarntzen** [Nabla-NTNU/nablaweb#578]
Wrong status on arrangement/mine/. It say: "Prikk! Eller du kommer til å få det.... ", but I did not get, and did not deserve any penalties: 
![Screen Shot 2022-02-01 at 14 31 17](https://user-images.githubusercontent.com/48533802/151977445-bff2f219-1ce8-4996-a5cd-3ab436419926.png)

**Comment by Famara72** [comment]
Endret tilbakemeldingen man får
