### ISSUE TITLE
Add link to purchase page in officeBeer

### ISSUE THREAD

**Issue by Northo** [Nabla-NTNU/nablaweb#603]
For administering officeBeer, we use /officeBeer/purchase/. However, that view should only be used by administrators (kjellerstyret), so there is no link there. However, we should add a link to purchase from /officeBeer/ for users with the correct permissions.

Hints:
- The permission is `officeBeer.sell_product`
- To find the URL of a given view, use Django's `reverse`
- The purchase-view has the name `officebeer_purchase`

**Comment by lovisesk** [comment]
e0ff15b6d8d7cd48be0bef37fbb3f2c91d0af4ba
This commit adds a button on /officebeer, that leads to /purchase, only visible for users with permission to purchase
