### ISSUE TITLE
Social media for comittees/groups

### ISSUE THREAD

**Issue by svemyh** [Nabla-NTNU/nablaweb#625]
Add a solution which adds links to the existing facebook- and -instagram-pages used by comittees/interest-groups. 
Perhaps it could be a single page with an overview of the groups, or adding links to existing comittee/group-pages.

**Comment by kwillno** [comment]
Could this be added as a tab( or section) of the existing contact page?  
Perhaps users should be able to add and remove group/social media links themselves? In that case we would need a more complex solution.

**Comment by svemyh** [comment]
Clickable icons have been added at the top of some of the group-pages. These are editable on the admin page by clikcing "Kilde". Although some knowledge in HMTL is recommended to edit. It is possible to copy icons between group-pages in order to add new ones.
