### ISSUE TITLE
Siden går for tidlig over til "telefonmeny"

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#63]
**[Original report](https://bitbucket.org/webkom/deprecated-nablaweb/issue/63) by Andreas Røssland (Bitbucket: [557058:06d22f7f-1c1a-4687-a750-e16dfe1eae15](https://bitbucket.org/557058:06d22f7f-1c1a-4687-a750-e16dfe1eae15), GitHub: [roessland](https://github.com/roessland)).**

----------------------------------------

"Telefonmenyen" er forøvrig litt teit, og kan endres hvis noen har forslag.

**Comment by alexarntzen** [comment]
Vi har nå det motsatte problemet
