### ISSUE TITLE
Nyhetsarkiv mangler

### ISSUE THREAD

**Issue by kaprests** [Nabla-NTNU/nablaweb#9]
**[Original report](https://bitbucket.org/webkom/deprecated-nablaweb/issue/9) by Andreas Røssland (Bitbucket: [557058:06d22f7f-1c1a-4687-a750-e16dfe1eae15](https://bitbucket.org/557058:06d22f7f-1c1a-4687-a750-e16dfe1eae15), GitHub: [roessland](https://github.com/roessland)).**

----------------------------------------

Det burde være en enkel måte å vise gamle nyheter.

For eksempel år og måneder i sidebaren, med lenker til å vise alle nyhetene fra en måned.

**Comment by alexarntzen** [comment]
Dette finnes vel nå som `flere nyheter`

**Comment by alexarntzen** [comment]
Så lukker denne
